package it.unicam.cs.mpgc.rpg125676.command.exploration;

import it.unicam.cs.mpgc.rpg125676.command.ActionResult;
import it.unicam.cs.mpgc.rpg125676.model.content.ContentDiscovery;
import it.unicam.cs.mpgc.rpg125676.model.content.RoomContent;
import it.unicam.cs.mpgc.rpg125676.model.entity.player.Player;
import it.unicam.cs.mpgc.rpg125676.model.game.GameState;
import it.unicam.cs.mpgc.rpg125676.model.game.dice.DiceRoller;
import it.unicam.cs.mpgc.rpg125676.model.world.Room;

import java.util.Objects;

/**
 * Searches the player's current room and discovers its content.
 * Only searchable rooms that have not already been searched can
 * be inspected. A valid search always discovers the room content.
 * The player's Caution and a dice roll determine whether the search
 * is silent or produces the configured search noise.
 */
public class SearchAction extends AbstractExplorationAction {

    private final DiceRoller diceRoller;

    /**
     * Creates a search action using the supplied dice roller.
     *
     * @param diceRoller dice roller used for the Caution check
     * @throws NullPointerException if diceRoller is null
     */
    public SearchAction(DiceRoller diceRoller) {
        this.diceRoller = Objects.requireNonNull(diceRoller);
    }

    @Override
    public String getName() {
        return "Search";
    }

    /**
     * Searches the player's current room and applies the discovered
     * content to the game state.
     * Any decision produced by the discovered content is registered
     * as a pending decision.
     *
     * @param state current game state
     * @return the result of the search
     * @throws IllegalStateException if a searchable room has no content
     */
    @Override
    protected ActionResult perform(GameState state) {
        Player player = state.getPlayer();
        Room room = player.getCurrentRoom();

        if (!room.isSearchable()) {
            return ActionResult.rejected("This room cannot be searched.");
        }

        if (room.isSearched()) {
            return ActionResult.rejected("This room has already been searched.");
        }

        RoomContent content = room.getContent().orElseThrow(() -> new IllegalStateException("Searchable room " + room.getId() + " has no content"));
        int noise = calculateSearchNoise(state);
        room.markAsSearched();
        ContentDiscovery discovery = content.discover(player, state.getSettings());
        discovery.pendingDecision().ifPresent(state::requestDecision);

        String message = "You searched " + room.getName() + ". " + discovery.message();

        if (noise == 0) {
            return ActionResult.silentSuccess(message);
        }
        return ActionResult.success(noise, room, message);
    }

    /**
     * Calculates the noise generated by the current search.
     * The search is silent when the dice roll combined with the
     * player's Caution reaches the configured threshold.
     *
     * @param state current game state
     * @return zero for a silent search, otherwise the configured
     *         search noise
     */
    private int calculateSearchNoise(GameState state) {
        int roll = diceRoller.roll();
        int caution = state.getPlayer().getStats().getCaution();
        int threshold = state.getSettings().search().silentSearchThreshold();

        if (roll + caution >= threshold) {return 0;}

        return state.getSettings().noise().searchNoise();
    }
}
