package it.unicam.cs.mpgc.rpg125676.command;

import it.unicam.cs.mpgc.rpg125676.model.world.Room;

import java.util.Objects;
import java.util.Optional;

/**
 * Describes the result produced by a game action.
 *
 * @param outcome     result of the action
 * @param noise       noise generated by the action
 * @param noiseSource room where the noise was generated
 * @param message     message describing the result
 */
public record ActionResult(ActionOutcome outcome, int noise, Optional<Room> noiseSource, String message) {

    /**
     * Validates the values used to create an action result.
     *
     * @throws NullPointerException if outcome, noiseSource or message is null
     * @throws IllegalArgumentException if noise is negative, if a silent
     *         result has a noise source or if a noisy result has no source
     */
    public ActionResult {
        Objects.requireNonNull(outcome);
        Objects.requireNonNull(noiseSource);
        Objects.requireNonNull(message);

        if (noise < 0) {throw new IllegalArgumentException("Noise cannot be negative");}
        if (noise == 0 && noiseSource.isPresent()) {
            throw new IllegalArgumentException("A silent action cannot have a noise source");
        }
        if (noise > 0 && noiseSource.isEmpty()) {throw new IllegalArgumentException("A noisy action must have a noise source");}
    }

    /**
     * Checks whether the action result consumes the current game turn.
     * Rejected actions do not consume a turn, while successful and
     * failed actions do.
     *
     * @return true if the action consumes the turn, false otherwise
     */
    public boolean consumesTurn() {
        return outcome != ActionOutcome.REJECTED;
    }

    /**
     * Checks whether the action completed successfully.
     *
     * @return true if the outcome is {@link ActionOutcome#SUCCESS},
     *         false otherwise
     */
    public boolean succeeded() {
        return outcome == ActionOutcome.SUCCESS;
    }

    /**
     * Creates a successful result for an action that generated noise.
     *
     * @param noise amount of noise generated by the action
     * @param noiseSource room in which the noise was produced
     * @param message message describing the successful result
     * @return a successful noisy action result
     */
    public static ActionResult success(int noise, Room noiseSource, String message) {
        return new ActionResult(ActionOutcome.SUCCESS, noise, Optional.of(noiseSource), message);
    }

    /**
     * Creates a successful result for an action that generated no noise.
     *
     * @param message message describing the successful result
     * @return a successful silent action result
     */
    public static ActionResult silentSuccess(String message) {
        return new ActionResult(ActionOutcome.SUCCESS, 0, Optional.empty(), message);
    }
    /**
     * Creates a failed result for an action that generated noise.
     * A failed action is considered executed and therefore consumes
     * the current game turn.
     * @param noise amount of noise generated by the action
     * @param noiseSource room in which the noise was produced
     * @param message message describing the failure
     * @return a failed noisy action result
     */
    public static ActionResult failure(int noise, Room noiseSource, String message) {
        return new ActionResult(ActionOutcome.FAILURE, noise, Optional.of(noiseSource), message);
    }

    /**
     * Creates a failed result for an action that generated no noise.
     * The action is considered executed and therefore consumes
     * the current game turn.
     *
     * @param message message describing the failure
     * @return a failed silent action result
     */
    public static ActionResult silentFailure(String message) {
        return new ActionResult(ActionOutcome.FAILURE, 0, Optional.empty(), message);
    }

    /**
     * Creates a result for an action that cannot be executed.
     * Rejected actions generate no noise and do not consume
     * the current game turn.
     *
     * @param message message explaining why the action was rejected
     * @return a rejected action result
     */
    public static ActionResult rejected(String message) {
        return new ActionResult(ActionOutcome.REJECTED, 0, Optional.empty(), message);
    }
}
