package it.unicam.cs.mpgc.rpg125676.model.content;

import it.unicam.cs.mpgc.rpg125676.model.game.decision.PendingDecision;

import java.util.Objects;
import java.util.Optional;

/**
 * Represents the result produced when room content is discovered.
 * A discovery always provides a descriptive message and may also
 * require an additional decision from the player.
 * @param message message describing the discovery result
 * @param pendingDecision optional decision that must be resolved by the player
 */
public record ContentDiscovery(String message, Optional<PendingDecision> pendingDecision) {

    /**
     * Validates the values used to create a discovery result.
     *
     * @throws NullPointerException if message or pendingDecision is null
     */
    public ContentDiscovery {
        Objects.requireNonNull(message);
        Objects.requireNonNull(pendingDecision);
    }

    /**
     * Creates a completed discovery that does not require
     * any additional player decision.
     *
     * @param message message describing the discovery
     * @return a completed discovery result
     * @throws NullPointerException if message is null
     */
    public static ContentDiscovery completed(String message) {
        return new ContentDiscovery(message, Optional.empty());
    }

    /**
     * Creates a discovery that requires an additional player decision.
     * The supplied decision is stored as pending and must be resolved
     * before normal game actions can continue.
     * @param message message describing the discovery
     * @param decision decision generated by the discovered content
     * @return a discovery result containing the pending decision
     * @throws NullPointerException if message or decision is null
     */
    public static ContentDiscovery requiringDecision(String message, PendingDecision decision) {
        return new ContentDiscovery(message, Optional.of(Objects.requireNonNull(decision)));
    }
}